from gensim.models import Word2Vec
story = [
    ["The", "Lantern", "in", "the", "Rain"],
    ["Every", "evening", "twelve-year-old", "Maya", "sat", "near", "the", "old", "railway", "bridge", "at", "the", "edge", "of", "her", "village"],
    ["The", "bridge", "had", "not", "carried", "a", "train", "in", "years", "but", "people", "still", "crossed", "it", "on", "foot"],
    ["Maya", "liked", "the", "place", "because", "it", "was", "quiet"],
    ["She", "could", "hear", "the", "river", "flowing", "below", "and", "birds", "calling", "from", "the", "trees"],
    ["One", "rainy", "evening", "Maya", "noticed", "a", "small", "lantern", "glowing", "beneath", "the", "bridge"],
    ["It", "swung", "gently", "in", "the", "wind", "even", "though", "no", "one", "seemed", "to", "be", "holding", "it"],
    ["Curious", "she", "climbed", "down", "the", "muddy", "path", "carefully"],
    ["Under", "the", "bridge", "sat", "an", "old", "man", "wrapped", "in", "a", "faded", "brown", "coat"],
    ["Beside", "him", "was", "a", "wooden", "cart", "filled", "with", "old", "clocks", "broken", "watches", "and", "tiny", "music", "boxes"],
    ["Good", "evening", "Maya", "said", "politely"],
    ["The", "old", "man", "looked", "up", "and", "smiled"],
    ["Not", "many", "people", "stop", "here", "anymore"],
    ["What", "are", "all", "these", "things", "she", "asked"],
    ["Lost", "things", "the", "old", "man", "replied"],
    ["Some", "people", "lose", "objects", "while", "others", "lose", "memories"],
    ["The", "old", "man", "picked", "up", "a", "small", "music", "box", "and", "turned", "its", "handle"],
    ["A", "soft", "melody", "floated", "through", "the", "air"],
    ["Suddenly", "Maya", "remembered", "her", "mother", "singing", "while", "baking", "bread", "in", "the", "kitchen"],
    ["Her", "mother", "had", "passed", "away", "when", "Maya", "was", "very", "young"],
    ["How", "did", "you", "do", "that", "Maya", "whispered"],
    ["Certain", "objects", "remember", "things", "better", "than", "people", "do"],
    ["Rain", "began", "pouring", "harder", "against", "the", "bridge"],
    ["Maya", "stayed", "there", "listening", "to", "more", "stories"],
    ["Every", "object", "carried", "a", "different", "story"],
    ["For", "the", "first", "time", "in", "many", "months", "Maya", "forgot", "about", "her", "loneliness"],
    ["As", "the", "storm", "calmed", "the", "old", "man", "lit", "another", "lantern"],
    ["He", "handed", "it", "to", "Maya"],
    ["Because", "everyone", "loses", "their", "way", "sometimes"],
    ["A", "lantern", "is", "useful", "when", "the", "world", "becomes", "dark"],
    ["The", "next", "evening", "Maya", "returned", "to", "the", "bridge"],
    ["But", "the", "old", "man", "was", "gone"],
    ["There", "was", "no", "cart", "and", "no", "music", "boxes"],
    ["Only", "the", "sound", "of", "the", "river", "remained"],
    ["Years", "passed", "and", "Maya", "became", "the", "village", "librarian"],
    ["She", "filled", "the", "library", "with", "stories", "letters", "photographs", "and", "forgotten", "histories"],
    ["Every", "rainy", "evening", "she", "placed", "the", "golden", "lantern", "in", "the", "library", "window"],
    ["It", "glowed", "softly", "for", "anyone", "who", "felt", "lost", "in", "the", "dark"]
]

model = Word2Vec(sentences=story,vector_size=100,sg=1,epochs=10,window=3,min_count=1)
print(model.wv.most_similar('library',topn=5))
